CREATE TABLE IF NOT EXISTS data_warehouse.members (
    idmember                        INTEGER         PRIMARY KEY,
    firstname                       VARCHAR(255),
    lastname                        VARCHAR(255),
    registername                    VARCHAR(255),
    registerlastname                VARCHAR(255),
    usepreferredname                BOOLEAN,
    registerdate                    TIMESTAMP,
    idbranch                        INTEGER,
    accessblocked                   BOOLEAN,
    blockedreason                   VARCHAR(255),
    document                        VARCHAR(20),
    documentid                      VARCHAR(20),
    maritalstatus                   VARCHAR(50),
    gender                          VARCHAR(20),
    birthdate                       TIMESTAMP,
    updatedate                      TIMESTAMP,
    totalfitcoins                   INTEGER,
    penalized                       BOOLEAN,
    status                          VARCHAR(50),
    lastaccessdate                  TIMESTAMP,
    conversiondate                  TIMESTAMP,
    idemployeeconsultant            INTEGER,
    idemployeeinstructor            INTEGER,
    photourl                        VARCHAR(500),
    personaltrainer                 BOOLEAN,
    clientwithpromotionalrestriction BOOLEAN,
    phone_ddi                       VARCHAR(10),
    phone                           VARCHAR(50),
    email                           VARCHAR(255),

    CONSTRAINT fk_members_branch        FOREIGN KEY (idbranch)             REFERENCES data_warehouse.dim_branch(branchid),
    CONSTRAINT fk_members_consultant    FOREIGN KEY (idemployeeconsultant) REFERENCES data_warehouse.dim_employee(idemployee),
    CONSTRAINT fk_members_instructor    FOREIGN KEY (idemployeeinstructor) REFERENCES data_warehouse.dim_employee(idemployee)
);
